### ISSUE TITLE
Thumbnail Missing

### ISSUE THREAD

**Issue by zawawimanja** [shouryakhare98/Rhyme-a-Zoo#18]
error: cannot find symbol
![capture](https://user-images.githubusercontent.com/37230267/53228334-db725c00-36bb-11e9-8563-9e7162c67306.PNG)
   R.drawable.thumbnail_

**Comment by shouryakhare98** [comment]
This project has not been finished yet. Please view the final application in May.

**Comment by shouryakhare98** [comment]
We just updated the repository and the app is functional.
